### ISSUE TITLE
Tests are failing on Node >= 0.12

### ISSUE THREAD

**Issue by sholladay** [sindresorhus/caller-path#1]
@sindresorhus 
See the [build status](https://travis-ci.org/sindresorhus/caller-path). Same thing is also happening [upstream](https://travis-ci.org/sindresorhus/caller-callsite).

**Comment by stevenvachon** [comment]
v1.0.0 fails on Node.js v4, but v0.1.0 works.

**Comment by sholladay** [comment]
ping @sindresorhus since you did another release and the tests are still failing, I'm just wondering if you are aware of this?

**Comment by stevenvachon** [comment]
@sindresorhus yo, wtf

**Comment by kevva** [comment]
There's PR with a fix for this here https://github.com/sindresorhus/caller-callsite/pull/1.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/caller-callsite/pull/1.
