### ISSUE TITLE
Missing license files

### ISSUE THREAD

**Issue by dariagrudzien** [sindresorhus/caller-path#5]
@sindresorhus Hi Sindre, thank you for this package. Would you mind adding the license file to the npm package of v0.1.0 and latest? Without it we're not really able to use it, because it makes the npm package a distribution of proprietary code.

Additionally I noticed the license file does not include the date, which makes it invalid. I'd greatly appreciate it if you could add the dates to the license files in GH repo as well.

Many thanks for your consideration.

**Comment by sindresorhus** [comment]
Same answer as https://github.com/sindresorhus/is-path-cwd/issues/5#issuecomment-435030426.

**Comment by patricksmms** [comment]
@sindresorhus, it's your own dependency (require-uncached) that is using the [outdated version of caller-path](https://npm.runkit.com/require-uncached/package.json?t=1541113143846).
